Ajustando ao repo padrão
betrybe/sd-0x-exercise-trybe-hotel-2 pull request #1
Opened 2023-08-17 21:39 UTC by TiagoPaz2000

2023-08-18 17:58 UTC, vinicius-vasconcelos requested changes
@TiagoPaz2000 Deixei algumas sugestões, pode ver se faz sentido por favor

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on .github/workflows/main.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
@TiagoPaz2000 eu peguei um docker-compose mais bem organizado, fiz algumas alterações! Veja se ficou melhor por favor?

Outro ponto subi a versão de algumas coisas:
- Fetch Jest evaluator: 9.2 -> 9.5
- Fetch Store evaluation: v6 -> v8

Alterei o step:
- Run Jest evaluation (alterei)

```suggestion
  evaluator:
    runs-on: self-hosted
    name: Evaluator
    services:
      mysql:
        image: mysql:8.0.23
        env:
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:    
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch ESLint evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/eslint-linter-action
          ref: v3.4
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/eslint-evaluator

      - name: Fetch Jest evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/jest-evaluator-action
          ref: v9.5
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/jest-evaluator

      - name: Fetch Store evaluation
        uses: actions/checkout@v2
        with:
          repository: betrybe/store-evaluation-action
          ref: v8.0
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/store-evaluation

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '16'

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'main'

      - name: Run ESLint evaluator
        uses: ./.github/actions/eslint-evaluator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}

      - name: Run Jest evaluation
        id: evaluator
        uses: ./.github/actions/jest-evaluator
        with:
          pr_author_username: ${{ github.event.pull_request.user.login }}
        env:
           DB_USER: 'root'
          DB_PASSWORD: 'password'
          DB_HOSTNAME: 'mysql'
          DB_DATABASE: 'store'
          DB_PORT: 3306

      - name: Run Store evaluation
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          token: ${{ secrets.GITHUB_TOKEN }}
```

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on .trybe/requirements.json
> +      "description": "2 - Crie uma `QUERY` que deve retornar as pessoas usuárias que sejam maior de idade.",
@TiagoPaz2000 Podemos alterar para pessoas que tenham mais de 18 anos?

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on README.md
> +Você deverá escrever as querys para resolver cada um dos exercícios, dentro do diretório src você encontrá os arquivos nos quais deverá escreve-las.
```suggestion
Você deverá escrever as queries para resolver cada um dos exercícios, dentro do diretório src você encontrá os arquivos nos quais deverá escreve-las.
```

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on README.md
> +- Use o comando `docker exec -it trybe_hotel_2 sh`.
@TiagoPaz2000 estamos seguindo o mesmo nome de contêineres do dia 1? Pergunto porque este termina com `_2` :thinking: 

Será que não faz sentido mantermos o mesmo nome?

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on README.md
> +  - Para rodar apenas um exercício rode `npm run test <número do exercício>`, por exemplo: para rodar apenas o exercício 7, você deverá rodar no terminal do container trybe_hotel_2 o comando `npm run
Mesma coisa aqui sobre o nome do container

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on README.md
> +- Crie uma `QUERY` que deve retornar as pessoas usuárias que sejam **maior de idade**.
@TiagoPaz2000 Podemos alterar para pessoas que tenham mais de 18 anos?

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on README.md
@TiagoPaz2000 não rola colocar um exemplo de resposta em uma tabela markdown?

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on docker-compose.yml
> +    container_name: trybe_hotel_2
A mesma coisa que eu havia falado lá em cima de usar o mesmo container que do dia 1, será que fica bom?

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on docker-compose.yml
> +      DB_DIALECT: 'mysql'
Atenção que eu alterei o arquivo `.github/main.ylm` ver se precisa refletir aqui ou mudar la

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on docker-compose.yml
> +    image: mysql:8.0
Podemo manter nessa versão? É a versão que estamos usando na seção

```suggestion
    image: mysql:8.0.23
```

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on trybe.yml
> +- tests
```suggestion
- tests/
```

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on trybe.yml
> +- package.json
```suggestion
- package.json
- .editorconfig
- .eslintignore
- .eslintrc.json
```

2023-08-18 17:58 UTC, vinicius-vasconcelos commented on .github/workflows/main.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
@renatosousafilho e @johnatas-henrique  veja se assim fica melhor

2023-08-18 18:13 UTC, TiagoPaz2000 commented on README.md
> +- Use o comando `docker exec -it trybe_hotel_2 sh`.
Oi @vinicius-vasconcelos. O problema pode ser uma falta de atenção das pessoas estudantes, porque se ela não apagar o container do dia anterior, o docker vai reclamar que o nome do container já está em uso.

2023-08-21 12:29 UTC, vinicius-vasconcelos commented on README.md
> +- Use o comando `docker exec -it trybe_hotel_2 sh`.
Isso é tranquilo! É até bom as pessoas tenham esse erro aqui, ok? Na minha visão podemos manter o mesmo nome, o que tu acha?

2023-08-21 16:11 UTC, TiagoPaz2000 commented on README.md
> +- Use o comando `docker exec -it trybe_hotel_2 sh`.
Então pode ser.

2023-08-21 18:28 UTC, vinicius-vasconcelos requested changes
@TiagoPaz2000 Terminei o CR, deixei algumas sugestões e o FAQ tem uma imagem quebrada, da uma olhada la fazendo favor :+1:

2023-08-21 18:28 UTC, vinicius-vasconcelos commented on README.md
> +Você deverá escrever as queries para resolver cada um dos exercícios, dentro do diretório src você encontrá os arquivos nos quais deverá escreve-las.
@TiagoPaz2000 é para escrever as queries no diretório `src` certo? Tem um outro diretório `Challenges` aqui :thinking: 

```suggestion
Você deverá escrever as queries para resolver cada um dos exercícios, dentro do diretório `src` você encontrá os arquivos nos quais deverá escreve-las.
```

2023-08-21 18:28 UTC, vinicius-vasconcelos commented on docker-compose.yml
> +      DB_PASSWORD: 'password'
Só mantendo a mesma senha do dia 1, ok?

```suggestion
      DB_PASSWORD: 'password123'
```

2023-08-21 18:28 UTC, vinicius-vasconcelos commented on tests/config/index.js
> +  DB_PASSWORD = 'password',
```suggestion
  DB_PASSWORD = 'password123',
```

2023-08-21 18:28 UTC, vinicius-vasconcelos commented on .github/workflows/main.yml
> +          DB_PASSWORD: 'password'
```suggestion
          DB_PASSWORD: 'password123'
```

2023-08-21 18:28 UTC, vinicius-vasconcelos commented on README.md
> +</details>
Último ponto man, não vale colocar uma saída esperada em formato de tabela aqui no README?

2023-08-22 18:40 UTC, renatosousafilho commented on README.md
> +  - Lembre-se de verificar se há outro container ou serviço rodando na porta (`3306`), se estiver, pare ele ou adapte no arquivo docker-compose.yml a porta mapeado do lado do host no serviço de db.
@TiagoPaz2000, eu não sei se alterar o docker-compose.yml é uma boa sugestão, pois acho que isso pode impactar no avaliador - não tenho certeza. 

Por via das dúvidas, acho interessante não dar tantas opções e dizer para pessoa simplesmente parar o container ou parar o serviço do mysql - caso a pessoa tenha instalado-o localmente. 

A gente já tem algum material que fale como fazer esse processo?

```suggestion
  - Lembre-se de verificar se há outro container ou serviço rodando na porta (`3306`). Se existir, libere a porta -encerrando o container ou o processo que estiver alocando a porta.
```

2023-08-22 18:42 UTC, renatosousafilho commented on README.md
> +> ⚠ Atenção ⚠ O **git** dentro do container não vem configurado com suas credenciais. Faça os commits fora do container, ou configure as suas credenciais do git dentro do container.
Aqui eu acho legal a gente diminuir as possibilidades para evitar que as pessoas estudantes evitem fazer coisas que não sabem como - ou que não tem necessidade.

```suggestion
> ⚠ Atenção ⚠ O **git** dentro do container não vem configurado com suas credenciais. Por isso, faça os commits em um terminal fora do container - ou seja, diretamente no _host_ da sua máquina.
```

2023-08-22 18:44 UTC, renatosousafilho commented on README.md
> +  <summary>Além disso, as seguintes verificações serão feitas:</summary>
Esse trecho `além disso `dá a ideia que a pessoa vai ter que fazer algo a mais do que está no enunciado. Podemos simplificar:

```suggestion
  <summary>As seguintes verificações serão feitas:</summary>
```

2023-08-22 18:45 UTC, renatosousafilho commented on README.md
> +- Crie uma `QUERY` que deve retornar as pessoas usuárias que tenham entre **30** e **39** anos.
O uso de verbos auxiliares como `vamos`, `deve` e coisas do tipo, deixa o texto muito prolixo. Podemos ir mais direto ao ponto - menos é mais!


```suggestion
- Crie uma `QUERY` que retorne as pessoas usuárias que tenham entre **30** e **39** anos.
```

2023-08-22 18:45 UTC, renatosousafilho commented on README.md
> +- Crie uma `QUERY` que deve retornar as pessoas usuárias que tenham mais de **18 anos**.
```suggestion
- Crie uma `QUERY` que retorna as pessoas usuárias que tenham mais de **18 anos**.
```

2023-08-22 18:45 UTC, renatosousafilho commented on README.md
> +  <summary>Além disso, as seguintes verificações serão feitas:</summary>
```suggestion
  <summary>As seguintes verificações serão feitas:</summary>
```

2023-08-22 18:47 UTC, renatosousafilho commented on README.md
> +- Crie uma `QUERY` que deve retornar o id, nome e sobrenome das pessoas usuárias que tenham se registrado no **ano de 2023**.
Aqui é importante deixar nítido o que é exatamente esperado, por isso coloque o **apenas**, tudo bem?

```suggestion
- Crie uma `QUERY` que retorna uma lista exibindo apenas o id, nome e sobrenome das pessoas usuárias que tenham se registrado no **ano de 2023**.
```

2023-08-22 18:47 UTC, renatosousafilho commented on README.md
> +  <summary>Além disso, as seguintes verificações serão feitas:</summary>
```suggestion
  <summary>As seguintes verificações serão feitas:</summary>
```

2023-08-22 18:48 UTC, renatosousafilho commented on README.md
> +- Crie uma `QUERY` que deve retornar as pessoas usuárias cujo **email** pertençam ao domínio **dotmail.com**.
```suggestion
- Crie uma `QUERY` que retorna  as pessoas usuárias cujo **email** pertençam ao domínio **dotmail.com**.
```

2023-08-22 18:48 UTC, renatosousafilho commented on README.md
> +  <summary>Além disso, as seguintes verificações serão feitas:</summary>
```suggestion
  <summary>As seguintes verificações serão feitas:</summary>
```

2023-08-22 18:49 UTC, renatosousafilho commented on README.md
> +- Crie uma `QUERY` que deve retornar as pessoas usuárias que tenham se registrado no entre as datas **01/06/2022** e **01/06/2023**.
Só dando uma simplificada no texto. 😉 

```suggestion
- Crie uma `QUERY` que retorna as pessoas usuárias cadastradas entre as datas **01/06/2022** e **01/06/2023**.
```

2023-08-22 18:50 UTC, renatosousafilho commented on README.md
> +  <summary>Além disso, as seguintes verificações serão feitas:</summary>
```suggestion
  <summary>As seguintes verificações serão feitas:</summary>
```

2023-08-22 18:52 UTC, renatosousafilho commented on README.md
> +- Crie uma `QUERY` que atualiza todas as pessoas usuárias que tenham **31 anos** para **32 anos**.
Para ficar mais alinhado com o conteúdo que escrevi, seria legal se o requisito pedir para alterar uma linha específica pelo id e não por um filtro de uma coluna que não é chave primária ou _UNIQUE_.

Vou atualizar o gabarito também.

```suggestion
- Crie uma `QUERY` que atualiza a idade da pessoa com `ìd` 1 para 32 anos.
```

2023-08-22 18:53 UTC, renatosousafilho commented on README.md
> +  <summary>Além disso, as seguintes verificações serão feitas:</summary>
```suggestion
  <summary>As seguintes verificações serão feitas:</summary>
```

2023-08-22 20:21 UTC, renatosousafilho requested changes
Paz, parabéns pelo empenho na construção desse exercício. Ficou muito bom e trago alguns pontos para deixar esse exercício ainda melhor.

### 1. Atenção para consistência no texto

Em alguns lugares é possível notar que não há uma consistência na forma que você escreve alguns códigos. Exemplo: tem lugar que você escreve um comando SQL em caixa alta, logo depois o mesmo comando em caixa baixa.

 É importante ficar atento a esses detalhes, pois eles dão uma impressão ruim para quem for ler. No CR, deixei várias sugestões de melhoria relacionados a esse ponto.

### 2. Faltou requisitos que exijam o uso de precedência de operadores lógicos e do operador IN

*Antes de ler essa parte, gostaria de pedir desculpas por não feito esse detalhamento antes de te delegar a tarefa. Seria mais simples para você executar se já tivesse uma ideia mais lapidada do que eu estava esperando. Na próxima sprint, vou combinar com o Vini da gente tentar deixar o começo do exercício como projeto, uma etapa após a produção dos artefatos de conteúdo. Isso evitará esse tipo de retrabalho que vou te pedir agora. Sei que é chato pedir refazer alguns requisitos, mas vou tentar ao máximo que não aconteça de novo, tudo bem?*

Ao ler os requisitos, percebi que eles seguem uma ordem, em que as habilidades necessárias para resolver cada um, não estão na mesma ordem que apresentamos no conteúdo.

É interessante a gente seguir a mesma ordem tanto no conteúdo como no exercício por que quando a P. Estudante for fazer o exercício ela pode ir acompanhando as lições e ir dando um *check* nas habilidades aprendidas. Isso gera uma sensação de aprendizado mais rápida e tira o gargalo da pessoa ter que ficar lembrando em qual parte do conteúdo está o que ela vai precisar para resolver cada requisito.

Logo sugiro que você faça uma refatoração nos requisito do 1 ao 6.

- Requisito 1: Solução utiliza apenas operadores relacionais - Aqui você pode reaproveitar o atual requisito 2.
- Requisito 2: Solução deve utilizar operadores lógicos como o `AND` ou `OR`. Não tem nenhum requisito desse tipo, será necessário criá-lo.
- Requisito 3: A solução deve abordar algo que utilize o conceito de precedência de operadores - ou seja um query que tenho o uso de OR combinado com `AND` e que precisa utilizar parênteses para gerar o resultado correto. Esse vai ser um requisito mais difícil. Não tem nenhum requisito desse tipo, será necessário criá-lo.
- Requisito 4: Deve ser um requisito sobre uso do LIKE. Como você já fez dois desse tipo, podemos escolher um e descartar o outro.
- Requisito 5: Requisito que pode ser resolvido com o uso do `IN`. Não tem nenhum requisito desse tipo, será necessário criá-lo.
- Requisito 6: Requisito que pode ser resolvido com o uso do `BETWEEN` - Temos dois, logo podemos descartar um.

### 3. Ficar atento para o texto não soar prolixo demais

Por último, é um dica de algo que aprendi nesse meio tempo que estou atuando produzindo conteúdo. É natural ao defender uma ideia que a gente busque o máximo de palavras para deixar nossa comunicação mais formal. 

Porém, tem um ponto que isso começa a atrapalhar mais do que ajudar. Por exemplo, uma frase longa demais ou muitas palavras para dar um exemplo. A dica é: menos é mais. Se tem uma informação que pode ser comunicada com menos palavras, não precisa florear demais para transmiti-la. Escreva apenas o suficiente.

Você notará que deixei vários feedbacks desse tipo. Não é algo que a gente muda da noite pro dia. São vícios de linguagem e é natural a gente se pegar repetindo esses vícios. Uma forma para lidar com isso é: Sempre que finalizar um texto, dar um tempo dele "respirar” - por exemplo de um dia para o outro - depois volta para ler ele de novo com um olhar crítico - como se você fosse uma P. Estudante que está lendo pela primeira vez aquilo. Isso com o tempo vai te ajudar a criar senso crítico e reconhecer os seus vícios. Eles nunca vão deixar de existir, mas reduzirão bastante se fizer essa leitura mais crítica.

---

### Recado final

Lembre-se que todos os feedbacks são visando que a gente entregue um conteúdo de excelência para as pessoas estudantes. Eles também servem como uma forma de você evoluir sua comunicação como um todo. Deixando nítido que você tem total espaço para discordar e fazer sugestões e com isso iremos convergir para uma solução conjunta, tudo bem?

Mais uma vez obrigado pela entrega e #vqv!

2023-08-23 21:46 UTC, TiagoPaz2000 commented on README.md
> +  - Lembre-se de verificar se há outro container ou serviço rodando na porta (`3306`), se estiver, pare ele ou adapte no arquivo docker-compose.yml a porta mapeado do lado do host no serviço de db.
Oi @renatosousafilho, não me lembro de ter nehum material sobre isso.

2023-08-23 21:56 UTC, TiagoPaz2000 commented on src/1-challenge.sql
> +SELECT * FROM users WHERE age between 30 and 39;
Oi @renatosousafilho , esses arquivos com código SQL são apenas temporários, pois são as resoluções do exercício, depois vou excluir eles do template.

2023-08-23 21:56 UTC, TiagoPaz2000 commented on tests/1-challenge.spec.js
> +  it('Verifica o exercício 1', async () => {
Oi @renatosousafilho , não entendi esse ponto.

2023-08-24 17:10 UTC, renatosousafilho commented on tests/1-challenge.spec.js
> +  it('Verifica o exercício 1', async () => {
@TiagoPaz2000 no caso, a sugestão é que tenh um `it` para cada um dos _bullet points_ que estão no README.

Exemplo

![Screenshot 2023-08-24 at 14 07 20](https://github.com/betrybe/sd-0x-exercise-trybe-hotel-2/assets/880182/f7c56317-48bf-4049-ac8a-2a63bfebe368)

No teste deveria ter dois its:

```js
it('Deve retornar uma lista com três itens.', async () => {
});

it('Os itens da lista devem ter os campos id, first_name, last_name, email, age, created_at.', async () => {
});
```

O racional é que quanto mais específico for o teste, menos espaço para eventuais falto positivo teremos. Por exemplo. Alguém pode fazer uma query que retorne as 3 linhas com o LIMIT e passar no primeiro it, mas se não corresponder ao que é esperado vai falhar no segundo teste.

2023-08-24 17:19 UTC, TiagoPaz2000 commented on tests/1-challenge.spec.js
> +  it('Verifica o exercício 1', async () => {
Ah sim, entendi agora @renatosousafilho. Faz sentindo sim.

2023-08-24 19:15 UTC, TiagoPaz2000 commented on tests/1-challenge.spec.js
> +  it('Verifica o exercício 1', async () => {
Oi @renatosousafilho, consegui adicionar esses testes, dá uma olhada como ficou.

Assim que os exercícios passarem do CR, eu adiciono esse ponto [aqui](https://github.com/betrybe/sd-0x-exercise-trybe-hotel-2/pull/1#discussion_r1302077794)

2023-08-24 20:03 UTC, renatosousafilho commented on tests/1-challenge.spec.js
> +  it('Verifica o exercício 1', async () => {
Show de bola @TiagoPaz2000, vou dar uma olhada aqui.

2023-08-24 20:10 UTC, renatosousafilho commented on README.md
Movi aqui para abaixo para o que estiver no item colapsado sejam só coisas relacionados ao que vai ser ferificado. Aproveitei para deixar o aviso importante seguindo as [quotes do MDI](https://github.com/betrybe/curriculo-system#quotes).

```suggestion
> **Atenção ⚠️:**  Tenha certeza de que o modo SQL_SAFE_UPDATES está desativado
```

2023-08-24 20:11 UTC, renatosousafilho commented on README.md
> +  - ***Obs: Tenha certeza de que o modo SQL_SAFE_UPDATES está desativado.***
Movi ali para abaixo e explico a razão.

```suggestion
```

2023-08-24 20:11 UTC, renatosousafilho commented on README.md
> +- ***Obs: Tenha certeza de que o modo SQL_SAFE_UPDATES está desativado.***
```suggestion
```

2023-08-24 20:11 UTC, renatosousafilho commented on README.md
Mesmo racional do requisito anterior.

```suggestion
> **Atenção ⚠️:**  Tenha certeza de que o modo SQL_SAFE_UPDATES está desativado
```

2023-08-24 20:12 UTC, renatosousafilho commented on README.md
> +</details>
```suggestion
</details>

> **Atenção ⚠️:**  Tenha certeza de que o modo SQL_SAFE_UPDATES está desativado
```

2023-08-24 20:12 UTC, renatosousafilho commented on README.md
> +- ***Obs: Tenha certeza de que o modo SQL_SAFE_UPDATES está desativado.***
```suggestion
```

2023-08-24 20:15 UTC, renatosousafilho commented on tests/5-challenge.spec.js
> +    const expectedResult = 3
```suggestion
    const expectedResult = 3;
```

2023-08-24 20:19 UTC, renatosousafilho commented on tests/5-challenge.spec.js
> +  it('Se apenas três linhas são atualizadas.', async () => {
Para quem for ler o log do teste, fica meio estranho esse `se`. Vou deixar a sugestão abaixo tanto aqui como no README. Além disso, uma boa prática para descrição de mensagens de teste é ter algum verbo para indicar o comportamento esperado. Você seguiu essa prática nos demais, mas aqui deu uma rápida desviada desse padrão.

```suggestion
  it('Deve atualizar três linhas.', async () => {
```

2023-08-24 20:19 UTC, renatosousafilho commented on tests/5-challenge.spec.js
> +  it('Se o campo created_at é atualizado com o valor correto.', async () => {
```suggestion
  it('Deve atualizar o valor do campo created_at para o valor informado.', async () => {
```

2023-08-24 20:21 UTC, renatosousafilho commented on README.md
> +  - Se apenas `três linhas` são atualizadas.
```suggestion
  - Deve atualizar três linhas.
```

2023-08-24 20:22 UTC, renatosousafilho commented on README.md
> +  - Se o campo `created_at` é atualizado com o valor correto.
```suggestion
  - Deve atualizar o valor do campo created_at para o valor informado.
```

2023-08-24 20:23 UTC, renatosousafilho requested changes
@TiagoPaz2000 fiz mais alguns leves ajustes. Veja se faz sentido.

2023-08-25 21:32 UTC, vinicius-vasconcelos approved these changes

2023-08-29 14:45 UTC, renatosousafilho approved these changes

2023-08-29 14:46 UTC, merged